### ISSUE TITLE
V1.8

### ISSUE THREAD

**Issue by Awagi** [Awagi/wiki-update-tracker#2]
# Plan for V1.8

## Overview

Pushing to protected branch is prohibited, so the bot will have to:
- push to a dedicated branch
- make a PR to merge changes in main branch

Also some features are missing like:
- static files like images aren't copied from original to translation file
- when an original file is removed, translation files aren't removed

## Todo List
- [x] Allow stub translation file creation on other branch
- [x] Implement PR auto create, update and close according to changes on dedicated branch
- [x] Add copy original files to translation files feature (in addition to stub creation)
- [x] Replace file-suffix input to something more globish
- [x] Add new "To Remove" translation file status and add support in tracker and updater
- [ ] ~~Add auto remove feature files for "To Remove"~~
  - instructing is just fine for now
- [x] Put templates in inputs?
- [x] Update documentation
- [ ] SonarQube quality and security improvement + OWASP dependency check
- [ ] Tests
